apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: raneenshub/spring-docker:secoendpush
        ports:
        - name: http
          containerPort: 8080
---         
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: petclinic-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: petclinic-service